### ISSUE TITLE
Unable to find a specification for `KindredSDK/Core`

### ISSUE THREAD

**Issue by voneddy** [kindred-app/Specs#1]
Hi,
Im trying to pod install RE: the [docs here](https://kindredsdkdocs.readme.io/docs/ios-core-sdk-documentation), and keep getting 

``` Unable to find a specification for `KindredSDK/Core` ```, im wondering if the url in ``` https://github.com/kindred-app/Specs/blob/master/KindredSDK/1.7.1/KindredSDK.podspec ``` is right? I'm no Pod dev, but is the ``` s.source = { :git => 'https://github.com/kindred-app/KindredSDK-Pod.git', :tag => s.version } ``` right?

I've added this lines 
``` source 'https://github.com/kindred-app/Specs.git' ```

and 

``` pod 'KindredSDK/Core' ``` 

To my podfile by the way.

Thanks for your time, all the best
Ed

**Comment by Vrushali-W** [comment]
Hi Ed,

Thank you for getting in touch. We will look into this issue and let you know what the best course of action is.
Can you please provide us a sample of your Podfile so that we can replicate this issue on our side? 

Regards,
Vrushali

**Comment by voneddy** [comment]
Sure Vrushali, it's pretty basic but here you go:
```
platform :ios, '11.0'
# source 'https://github.com/voneddy/Specs.git' <-- my fork with the s.source change above?
source 'https://github.com/kindred-app/Specs.git'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  pod 'KindredSDK/Core'
end

target 'PluginTests' do
  capacitor_pods
end

```
Hoping in a way i missed something simple?

I'm just going ``` pod install ``` which gives 
```
Analyzing dependencies
[!] Unable to find a specification for `KindredSDK/Core`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile
```
Pretty sure ``` https://github.com/kindred-app/KindredSDK-Pod.git ``` needs to exist / not be private? 
All the best
Ed

**Comment by Vrushali-W** [comment]
Hi Eddy,

We have resolved the issue and you should be able to install the pod.

Kind regards,
Vrushali
